import express from "express";
const router  = express.Router();
import getReq from "./todosget.js";
import delleteReq from "./deletetodos.js";
import postReq from "./addtodos.js";
import putReq from "./update.js";
router.use("/todos" , getReq);
router.use("/todos" , putReq);
router.use("/todos" , postReq);
router.use("/todos" , delleteReq);
export default router;